"""baseline — full schema as of 0.5.0

Revision ID: 7500d72e9360
Revises: 
Create Date: 2026-06-12 04:27:44.858831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7500d72e9360'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rename_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_file_id', sa.Integer(), nullable=True),
    sa.Column('src', sa.String(), nullable=False),
    sa.Column('dst', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_path', sa.String(), nullable=False),
    sa.Column('source', sa.String(), server_default='manual', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('estimated_total', sa.Integer(), nullable=True),
    sa.Column('current_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('series_key', sa.String(), nullable=True),
    sa.Column('variant_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_files_series_key'), ['series_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_variant_key'), ['variant_key'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_file_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('series_group_id', sa.String(), nullable=True),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('series_name', sa.String(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('episode_title', sa.String(), nullable=True),
    sa.Column('poster_url', sa.String(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('collection_id', sa.String(), nullable=True),
    sa.Column('collection_name', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_series_group_id'), ['series_group_id'], unique=False)

    op.create_table('rename_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_file_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('old_path', sa.String(), nullable=False),
    sa.Column('new_path', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('template_used', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('poster_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('undone_at', sa.DateTime(), nullable=True),
    sa.Column('created_assets', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['rename_history.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rename_history')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_series_group_id'))
        batch_op.drop_index(batch_op.f('ix_matches_collection_id'))

    op.drop_table('matches')
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_files_variant_key'))
        batch_op.drop_index(batch_op.f('ix_media_files_series_key'))

    op.drop_table('media_files')
    op.drop_table('settings')
    op.drop_table('scans')
    op.drop_table('rename_intents')
    op.drop_table('notifications')
    # ### end Alembic commands ###
